// <auto-generated/>
#pragma warning disable CS0618
using MealieMcp.Clients.Api.Households.Cookbooks.Item;
using MealieMcp.Clients.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MealieMcp.Clients.Api.Households.Cookbooks
{
    /// <summary>
    /// Builds and executes requests for operations under \api\households\cookbooks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CookbooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MealieMcp.Clients.api.households.cookbooks.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MealieMcp.Clients.Api.Households.Cookbooks.Item.WithItem_ItemRequestBuilder"/></returns>
        public global::MealieMcp.Clients.Api.Households.Cookbooks.Item.WithItem_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("item_id", position);
                return new global::MealieMcp.Clients.Api.Households.Cookbooks.Item.WithItem_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CookbooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households/cookbooks{?orderBy*,orderByNullPosition*,orderDirection*,page*,paginationSeed*,perPage*,queryFilter*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CookbooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households/cookbooks{?orderBy*,orderByNullPosition*,orderDirection*,page*,paginationSeed*,perPage*,queryFilter*}", rawUrl)
        {
        }
        /// <summary>
        /// Get All
        /// </summary>
        /// <returns>A <see cref="global::MealieMcp.Clients.Models.CookBookPagination"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MealieMcp.Clients.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MealieMcp.Clients.Models.CookBookPagination?> GetAsync(Action<RequestConfiguration<global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MealieMcp.Clients.Models.CookBookPagination> GetAsync(Action<RequestConfiguration<global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::MealieMcp.Clients.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MealieMcp.Clients.Models.CookBookPagination>(requestInfo, global::MealieMcp.Clients.Models.CookBookPagination.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create One
        /// </summary>
        /// <returns>A <see cref="global::MealieMcp.Clients.Models.ReadCookBook"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MealieMcp.Clients.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MealieMcp.Clients.Models.ReadCookBook?> PostAsync(global::MealieMcp.Clients.Models.CreateCookBook body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MealieMcp.Clients.Models.ReadCookBook> PostAsync(global::MealieMcp.Clients.Models.CreateCookBook body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::MealieMcp.Clients.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MealieMcp.Clients.Models.ReadCookBook>(requestInfo, global::MealieMcp.Clients.Models.ReadCookBook.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update Many
        /// </summary>
        /// <returns>A List&lt;global::MealieMcp.Clients.Models.ReadCookBook&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MealieMcp.Clients.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::MealieMcp.Clients.Models.ReadCookBook>?> PutAsync(List<global::MealieMcp.Clients.Models.UpdateCookBook> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::MealieMcp.Clients.Models.ReadCookBook>> PutAsync(List<global::MealieMcp.Clients.Models.UpdateCookBook> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::MealieMcp.Clients.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::MealieMcp.Clients.Models.ReadCookBook>(requestInfo, global::MealieMcp.Clients.Models.ReadCookBook.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Get All
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create One
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MealieMcp.Clients.Models.CreateCookBook body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MealieMcp.Clients.Models.CreateCookBook body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Update Many
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(List<global::MealieMcp.Clients.Models.UpdateCookBook> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(List<global::MealieMcp.Clients.Models.UpdateCookBook> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get All
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CookbooksRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderByNullPosition")]
            public string? OrderByNullPosition { get; set; }
#nullable restore
#else
            [QueryParameter("orderByNullPosition")]
            public string OrderByNullPosition { get; set; }
#endif
            [Obsolete("This property is deprecated, use OrderDirectionAsOrderDirection instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderDirection")]
            public string? OrderDirection { get; set; }
#nullable restore
#else
            [QueryParameter("orderDirection")]
            public string OrderDirection { get; set; }
#endif
            [QueryParameter("orderDirection")]
            public global::MealieMcp.Clients.Models.OrderDirection? OrderDirectionAsOrderDirection { get; set; }
            [QueryParameter("page")]
            public int? Page { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("paginationSeed")]
            public string? PaginationSeed { get; set; }
#nullable restore
#else
            [QueryParameter("paginationSeed")]
            public string PaginationSeed { get; set; }
#endif
            [QueryParameter("perPage")]
            public int? PerPage { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("queryFilter")]
            public string? QueryFilter { get; set; }
#nullable restore
#else
            [QueryParameter("queryFilter")]
            public string QueryFilter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CookbooksRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CookbooksRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CookbooksRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
