// <auto-generated/>
#pragma warning disable CS0618
using MealieMcp.Clients.Api.Groups.Seeders.Foods;
using MealieMcp.Clients.Api.Groups.Seeders.Labels;
using MealieMcp.Clients.Api.Groups.Seeders.Units;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealieMcp.Clients.Api.Groups.Seeders
{
    /// <summary>
    /// Builds and executes requests for operations under \api\groups\seeders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SeedersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The foods property</summary>
        public global::MealieMcp.Clients.Api.Groups.Seeders.Foods.FoodsRequestBuilder Foods
        {
            get => new global::MealieMcp.Clients.Api.Groups.Seeders.Foods.FoodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The labels property</summary>
        public global::MealieMcp.Clients.Api.Groups.Seeders.Labels.LabelsRequestBuilder Labels
        {
            get => new global::MealieMcp.Clients.Api.Groups.Seeders.Labels.LabelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The units property</summary>
        public global::MealieMcp.Clients.Api.Groups.Seeders.Units.UnitsRequestBuilder Units
        {
            get => new global::MealieMcp.Clients.Api.Groups.Seeders.Units.UnitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Groups.Seeders.SeedersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeedersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/groups/seeders", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Groups.Seeders.SeedersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeedersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/groups/seeders", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
