// <auto-generated/>
#pragma warning disable CS0618
using MealieMcp.Clients.Api.Admin;
using MealieMcp.Clients.Api.App;
using MealieMcp.Clients.Api.Auth;
using MealieMcp.Clients.Api.Comments;
using MealieMcp.Clients.Api.Explore;
using MealieMcp.Clients.Api.Foods;
using MealieMcp.Clients.Api.Groups;
using MealieMcp.Clients.Api.Households;
using MealieMcp.Clients.Api.Media;
using MealieMcp.Clients.Api.Organizers;
using MealieMcp.Clients.Api.Parser;
using MealieMcp.Clients.Api.Recipes;
using MealieMcp.Clients.Api.Shared;
using MealieMcp.Clients.Api.Units;
using MealieMcp.Clients.Api.Users;
using MealieMcp.Clients.Api.Utils;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealieMcp.Clients.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The admin property</summary>
        public global::MealieMcp.Clients.Api.Admin.AdminRequestBuilder Admin
        {
            get => new global::MealieMcp.Clients.Api.Admin.AdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The app property</summary>
        public global::MealieMcp.Clients.Api.App.AppRequestBuilder App
        {
            get => new global::MealieMcp.Clients.Api.App.AppRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::MealieMcp.Clients.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::MealieMcp.Clients.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comments property</summary>
        public global::MealieMcp.Clients.Api.Comments.CommentsRequestBuilder Comments
        {
            get => new global::MealieMcp.Clients.Api.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The explore property</summary>
        public global::MealieMcp.Clients.Api.Explore.ExploreRequestBuilder Explore
        {
            get => new global::MealieMcp.Clients.Api.Explore.ExploreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The foods property</summary>
        public global::MealieMcp.Clients.Api.Foods.FoodsRequestBuilder Foods
        {
            get => new global::MealieMcp.Clients.Api.Foods.FoodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::MealieMcp.Clients.Api.Groups.GroupsRequestBuilder Groups
        {
            get => new global::MealieMcp.Clients.Api.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The households property</summary>
        public global::MealieMcp.Clients.Api.Households.HouseholdsRequestBuilder Households
        {
            get => new global::MealieMcp.Clients.Api.Households.HouseholdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The media property</summary>
        public global::MealieMcp.Clients.Api.Media.MediaRequestBuilder Media
        {
            get => new global::MealieMcp.Clients.Api.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizers property</summary>
        public global::MealieMcp.Clients.Api.Organizers.OrganizersRequestBuilder Organizers
        {
            get => new global::MealieMcp.Clients.Api.Organizers.OrganizersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The parser property</summary>
        public global::MealieMcp.Clients.Api.Parser.ParserRequestBuilder Parser
        {
            get => new global::MealieMcp.Clients.Api.Parser.ParserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recipes property</summary>
        public global::MealieMcp.Clients.Api.Recipes.RecipesRequestBuilder Recipes
        {
            get => new global::MealieMcp.Clients.Api.Recipes.RecipesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shared property</summary>
        public global::MealieMcp.Clients.Api.Shared.SharedRequestBuilder Shared
        {
            get => new global::MealieMcp.Clients.Api.Shared.SharedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The units property</summary>
        public global::MealieMcp.Clients.Api.Units.UnitsRequestBuilder Units
        {
            get => new global::MealieMcp.Clients.Api.Units.UnitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::MealieMcp.Clients.Api.Users.UsersRequestBuilder Users
        {
            get => new global::MealieMcp.Clients.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The utils property</summary>
        public global::MealieMcp.Clients.Api.Utils.UtilsRequestBuilder Utils
        {
            get => new global::MealieMcp.Clients.Api.Utils.UtilsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
