// <auto-generated/>
#pragma warning disable CS0618
using MealieMcp.Clients.Api.Households.Cookbooks;
using MealieMcp.Clients.Api.Households.Events;
using MealieMcp.Clients.Api.Households.Invitations;
using MealieMcp.Clients.Api.Households.Mealplans;
using MealieMcp.Clients.Api.Households.Members;
using MealieMcp.Clients.Api.Households.Permissions;
using MealieMcp.Clients.Api.Households.Preferences;
using MealieMcp.Clients.Api.Households.RecipeActions;
using MealieMcp.Clients.Api.Households.Self;
using MealieMcp.Clients.Api.Households.Shopping;
using MealieMcp.Clients.Api.Households.Statistics;
using MealieMcp.Clients.Api.Households.Webhooks;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealieMcp.Clients.Api.Households
{
    /// <summary>
    /// Builds and executes requests for operations under \api\households
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HouseholdsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cookbooks property</summary>
        public global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder Cookbooks
        {
            get => new global::MealieMcp.Clients.Api.Households.Cookbooks.CookbooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::MealieMcp.Clients.Api.Households.Events.EventsRequestBuilder Events
        {
            get => new global::MealieMcp.Clients.Api.Households.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invitations property</summary>
        public global::MealieMcp.Clients.Api.Households.Invitations.InvitationsRequestBuilder Invitations
        {
            get => new global::MealieMcp.Clients.Api.Households.Invitations.InvitationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mealplans property</summary>
        public global::MealieMcp.Clients.Api.Households.Mealplans.MealplansRequestBuilder Mealplans
        {
            get => new global::MealieMcp.Clients.Api.Households.Mealplans.MealplansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::MealieMcp.Clients.Api.Households.Members.MembersRequestBuilder Members
        {
            get => new global::MealieMcp.Clients.Api.Households.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::MealieMcp.Clients.Api.Households.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::MealieMcp.Clients.Api.Households.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preferences property</summary>
        public global::MealieMcp.Clients.Api.Households.Preferences.PreferencesRequestBuilder Preferences
        {
            get => new global::MealieMcp.Clients.Api.Households.Preferences.PreferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recipeActions property</summary>
        public global::MealieMcp.Clients.Api.Households.RecipeActions.RecipeActionsRequestBuilder RecipeActions
        {
            get => new global::MealieMcp.Clients.Api.Households.RecipeActions.RecipeActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The self property</summary>
        public global::MealieMcp.Clients.Api.Households.Self.SelfRequestBuilder Self
        {
            get => new global::MealieMcp.Clients.Api.Households.Self.SelfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shopping property</summary>
        public global::MealieMcp.Clients.Api.Households.Shopping.ShoppingRequestBuilder Shopping
        {
            get => new global::MealieMcp.Clients.Api.Households.Shopping.ShoppingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statistics property</summary>
        public global::MealieMcp.Clients.Api.Households.Statistics.StatisticsRequestBuilder Statistics
        {
            get => new global::MealieMcp.Clients.Api.Households.Statistics.StatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::MealieMcp.Clients.Api.Households.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::MealieMcp.Clients.Api.Households.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Households.HouseholdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HouseholdsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Households.HouseholdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HouseholdsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
