// <auto-generated/>
#pragma warning disable CS0618
using MealieMcp.Clients.Api.Groups.Households;
using MealieMcp.Clients.Api.Groups.Labels;
using MealieMcp.Clients.Api.Groups.Members;
using MealieMcp.Clients.Api.Groups.Migrations;
using MealieMcp.Clients.Api.Groups.Preferences;
using MealieMcp.Clients.Api.Groups.Reports;
using MealieMcp.Clients.Api.Groups.Seeders;
using MealieMcp.Clients.Api.Groups.Self;
using MealieMcp.Clients.Api.Groups.Storage;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealieMcp.Clients.Api.Groups
{
    /// <summary>
    /// Builds and executes requests for operations under \api\groups
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GroupsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The households property</summary>
        public global::MealieMcp.Clients.Api.Groups.Households.HouseholdsRequestBuilder Households
        {
            get => new global::MealieMcp.Clients.Api.Groups.Households.HouseholdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The labels property</summary>
        public global::MealieMcp.Clients.Api.Groups.Labels.LabelsRequestBuilder Labels
        {
            get => new global::MealieMcp.Clients.Api.Groups.Labels.LabelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::MealieMcp.Clients.Api.Groups.Members.MembersRequestBuilder Members
        {
            get => new global::MealieMcp.Clients.Api.Groups.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The migrations property</summary>
        public global::MealieMcp.Clients.Api.Groups.Migrations.MigrationsRequestBuilder Migrations
        {
            get => new global::MealieMcp.Clients.Api.Groups.Migrations.MigrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preferences property</summary>
        public global::MealieMcp.Clients.Api.Groups.Preferences.PreferencesRequestBuilder Preferences
        {
            get => new global::MealieMcp.Clients.Api.Groups.Preferences.PreferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reports property</summary>
        public global::MealieMcp.Clients.Api.Groups.Reports.ReportsRequestBuilder Reports
        {
            get => new global::MealieMcp.Clients.Api.Groups.Reports.ReportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seeders property</summary>
        public global::MealieMcp.Clients.Api.Groups.Seeders.SeedersRequestBuilder Seeders
        {
            get => new global::MealieMcp.Clients.Api.Groups.Seeders.SeedersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The self property</summary>
        public global::MealieMcp.Clients.Api.Groups.Self.SelfRequestBuilder Self
        {
            get => new global::MealieMcp.Clients.Api.Groups.Self.SelfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storage property</summary>
        public global::MealieMcp.Clients.Api.Groups.Storage.StorageRequestBuilder Storage
        {
            get => new global::MealieMcp.Clients.Api.Groups.Storage.StorageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Groups.GroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/groups", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Api.Groups.GroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/groups", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
