// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MealieMcp.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PlanRulesType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "breakfast")]
        #pragma warning disable CS1591
        Breakfast,
        #pragma warning restore CS1591
        [EnumMember(Value = "lunch")]
        #pragma warning disable CS1591
        Lunch,
        #pragma warning restore CS1591
        [EnumMember(Value = "dinner")]
        #pragma warning disable CS1591
        Dinner,
        #pragma warning restore CS1591
        [EnumMember(Value = "side")]
        #pragma warning disable CS1591
        Side,
        #pragma warning restore CS1591
        [EnumMember(Value = "snack")]
        #pragma warning disable CS1591
        Snack,
        #pragma warning restore CS1591
        [EnumMember(Value = "drink")]
        #pragma warning disable CS1591
        Drink,
        #pragma warning restore CS1591
        [EnumMember(Value = "dessert")]
        #pragma warning disable CS1591
        Dessert,
        #pragma warning restore CS1591
        [EnumMember(Value = "unset")]
        #pragma warning disable CS1591
        Unset,
        #pragma warning restore CS1591
    }
}
