// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealieMcp.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlanRulesOut : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The day property</summary>
        public global::MealieMcp.Clients.Models.PlanRulesDay? Day { get; set; }
        /// <summary>The entryType property</summary>
        public global::MealieMcp.Clients.Models.PlanRulesType? EntryType { get; set; }
        /// <summary>The groupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The householdId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseholdId { get; set; }
#nullable restore
#else
        public string HouseholdId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The queryFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.QueryFilterJSON? QueryFilter { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.QueryFilterJSON QueryFilter { get; set; }
#endif
        /// <summary>The queryFilterString property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QueryFilterString { get; set; }
#nullable restore
#else
        public string QueryFilterString { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Models.PlanRulesOut"/> and sets the default values.
        /// </summary>
        public PlanRulesOut()
        {
            AdditionalData = new Dictionary<string, object>();
            Day = global::MealieMcp.Clients.Models.PlanRulesDay.Unset;
            EntryType = global::MealieMcp.Clients.Models.PlanRulesType.Unset;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealieMcp.Clients.Models.PlanRulesOut"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealieMcp.Clients.Models.PlanRulesOut CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealieMcp.Clients.Models.PlanRulesOut();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "day", n => { Day = n.GetEnumValue<global::MealieMcp.Clients.Models.PlanRulesDay>(); } },
                { "entryType", n => { EntryType = n.GetEnumValue<global::MealieMcp.Clients.Models.PlanRulesType>(); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "householdId", n => { HouseholdId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "queryFilter", n => { QueryFilter = n.GetObjectValue<global::MealieMcp.Clients.Models.QueryFilterJSON>(global::MealieMcp.Clients.Models.QueryFilterJSON.CreateFromDiscriminatorValue); } },
                { "queryFilterString", n => { QueryFilterString = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::MealieMcp.Clients.Models.PlanRulesDay>("day", Day);
            writer.WriteEnumValue<global::MealieMcp.Clients.Models.PlanRulesType>("entryType", EntryType);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("householdId", HouseholdId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.QueryFilterJSON>("queryFilter", QueryFilter);
            writer.WriteStringValue("queryFilterString", QueryFilterString);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
