// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealieMcp.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecipeSummary : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cookTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CookTime { get; set; }
#nullable restore
#else
        public string CookTime { get; set; }
#endif
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt? CreatedAt { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt CreatedAt { get; set; }
#endif
        /// <summary>The dateAdded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded? DateAdded { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded DateAdded { get; set; }
#endif
        /// <summary>The dateUpdated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated? DateUpdated { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated DateUpdated { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The groupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The householdId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseholdId { get; set; }
#nullable restore
#else
        public string HouseholdId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Image { get; set; }
#nullable restore
#else
        public UntypedNode Image { get; set; }
#endif
        /// <summary>The lastMade property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade? LastMade { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade LastMade { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The orgURL property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgURL { get; set; }
#nullable restore
#else
        public string OrgURL { get; set; }
#endif
        /// <summary>The performTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PerformTime { get; set; }
#nullable restore
#else
        public string PerformTime { get; set; }
#endif
        /// <summary>The prepTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrepTime { get; set; }
#nullable restore
#else
        public string PrepTime { get; set; }
#endif
        /// <summary>The rating property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rating { get; set; }
#nullable restore
#else
        public string Rating { get; set; }
#endif
        /// <summary>The recipeCategory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealieMcp.Clients.Models.RecipeCategory>? RecipeCategory { get; set; }
#nullable restore
#else
        public List<global::MealieMcp.Clients.Models.RecipeCategory> RecipeCategory { get; set; }
#endif
        /// <summary>The recipeServings property</summary>
        public double? RecipeServings { get; set; }
        /// <summary>The recipeYield property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipeYield { get; set; }
#nullable restore
#else
        public string RecipeYield { get; set; }
#endif
        /// <summary>The recipeYieldQuantity property</summary>
        public double? RecipeYieldQuantity { get; set; }
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealieMcp.Clients.Models.RecipeTag>? Tags { get; set; }
#nullable restore
#else
        public List<global::MealieMcp.Clients.Models.RecipeTag> Tags { get; set; }
#endif
        /// <summary>The tools property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealieMcp.Clients.Models.RecipeTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::MealieMcp.Clients.Models.RecipeTool> Tools { get; set; }
#endif
        /// <summary>The totalTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalTime { get; set; }
#nullable restore
#else
        public string TotalTime { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt? UpdatedAt { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt UpdatedAt { get; set; }
#endif
        /// <summary>The userId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Models.RecipeSummary"/> and sets the default values.
        /// </summary>
        public RecipeSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealieMcp.Clients.Models.RecipeSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealieMcp.Clients.Models.RecipeSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealieMcp.Clients.Models.RecipeSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cookTime", n => { CookTime = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt>(global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt.CreateFromDiscriminatorValue); } },
                { "dateAdded", n => { DateAdded = n.GetObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded>(global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded.CreateFromDiscriminatorValue); } },
                { "dateUpdated", n => { DateUpdated = n.GetObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated>(global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "householdId", n => { HouseholdId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "lastMade", n => { LastMade = n.GetObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade>(global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orgURL", n => { OrgURL = n.GetStringValue(); } },
                { "performTime", n => { PerformTime = n.GetStringValue(); } },
                { "prepTime", n => { PrepTime = n.GetStringValue(); } },
                { "rating", n => { Rating = n.GetStringValue(); } },
                { "recipeCategory", n => { RecipeCategory = n.GetCollectionOfObjectValues<global::MealieMcp.Clients.Models.RecipeCategory>(global::MealieMcp.Clients.Models.RecipeCategory.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recipeServings", n => { RecipeServings = n.GetDoubleValue(); } },
                { "recipeYield", n => { RecipeYield = n.GetStringValue(); } },
                { "recipeYieldQuantity", n => { RecipeYieldQuantity = n.GetDoubleValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::MealieMcp.Clients.Models.RecipeTag>(global::MealieMcp.Clients.Models.RecipeTag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::MealieMcp.Clients.Models.RecipeTool>(global::MealieMcp.Clients.Models.RecipeTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalTime", n => { TotalTime = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt>(global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cookTime", CookTime);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt>("createdAt", CreatedAt);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded>("dateAdded", DateAdded);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated>("dateUpdated", DateUpdated);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("householdId", HouseholdId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<UntypedNode>("image", Image);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade>("lastMade", LastMade);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("orgURL", OrgURL);
            writer.WriteStringValue("performTime", PerformTime);
            writer.WriteStringValue("prepTime", PrepTime);
            writer.WriteStringValue("rating", Rating);
            writer.WriteCollectionOfObjectValues<global::MealieMcp.Clients.Models.RecipeCategory>("recipeCategory", RecipeCategory);
            writer.WriteDoubleValue("recipeServings", RecipeServings);
            writer.WriteStringValue("recipeYield", RecipeYield);
            writer.WriteDoubleValue("recipeYieldQuantity", RecipeYieldQuantity);
            writer.WriteStringValue("slug", Slug);
            writer.WriteCollectionOfObjectValues<global::MealieMcp.Clients.Models.RecipeTag>("tags", Tags);
            writer.WriteCollectionOfObjectValues<global::MealieMcp.Clients.Models.RecipeTool>("tools", Tools);
            writer.WriteStringValue("totalTime", TotalTime);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt>("updatedAt", UpdatedAt);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealieMcp.Clients.Models.RecipeSummary_createdAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeSummary_createdAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.RecipeSummary_createdAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.RecipeSummary_createdAtMember1? RecipeSummaryCreatedAtMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.RecipeSummary_createdAtMember1 RecipeSummaryCreatedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_createdAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.RecipeSummaryCreatedAtMember1 = new global::MealieMcp.Clients.Models.RecipeSummary_createdAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeSummaryCreatedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeSummaryCreatedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary_createdAtMember1>(null, RecipeSummaryCreatedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="Date"/>, <see cref="global::MealieMcp.Clients.Models.RecipeSummary_dateAddedMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeSummary_dateAdded : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="Date"/></summary>
            public Date? DateOnly { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.RecipeSummary_dateAddedMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.RecipeSummary_dateAddedMember1? RecipeSummaryDateAddedMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.RecipeSummary_dateAddedMember1 RecipeSummaryDateAddedMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateAdded();
                if(parseNode.GetDateValue() is Date dateOnlyValue)
                {
                    result.DateOnly = dateOnlyValue;
                }
                else {
                    result.RecipeSummaryDateAddedMember1 = new global::MealieMcp.Clients.Models.RecipeSummary_dateAddedMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeSummaryDateAddedMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeSummaryDateAddedMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateOnly != null)
                {
                    writer.WriteDateValue(null, DateOnly);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary_dateAddedMember1>(null, RecipeSummaryDateAddedMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealieMcp.Clients.Models.RecipeSummary_dateUpdatedMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeSummary_dateUpdated : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.RecipeSummary_dateUpdatedMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.RecipeSummary_dateUpdatedMember1? RecipeSummaryDateUpdatedMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.RecipeSummary_dateUpdatedMember1 RecipeSummaryDateUpdatedMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_dateUpdated();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.RecipeSummaryDateUpdatedMember1 = new global::MealieMcp.Clients.Models.RecipeSummary_dateUpdatedMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeSummaryDateUpdatedMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeSummaryDateUpdatedMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary_dateUpdatedMember1>(null, RecipeSummaryDateUpdatedMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealieMcp.Clients.Models.RecipeSummary_lastMadeMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeSummary_lastMade : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.RecipeSummary_lastMadeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.RecipeSummary_lastMadeMember1? RecipeSummaryLastMadeMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.RecipeSummary_lastMadeMember1 RecipeSummaryLastMadeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_lastMade();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.RecipeSummaryLastMadeMember1 = new global::MealieMcp.Clients.Models.RecipeSummary_lastMadeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeSummaryLastMadeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeSummaryLastMadeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary_lastMadeMember1>(null, RecipeSummaryLastMadeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealieMcp.Clients.Models.RecipeSummary_updatedAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeSummary_updatedAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.RecipeSummary_updatedAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.RecipeSummary_updatedAtMember1? RecipeSummaryUpdatedAtMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.RecipeSummary_updatedAtMember1 RecipeSummaryUpdatedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.RecipeSummary.RecipeSummary_updatedAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.RecipeSummaryUpdatedAtMember1 = new global::MealieMcp.Clients.Models.RecipeSummary_updatedAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeSummaryUpdatedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeSummaryUpdatedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeSummary_updatedAtMember1>(null, RecipeSummaryUpdatedAtMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
