// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealieMcp.Clients.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShoppingListItemOutOutput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checked property</summary>
        public bool? Checked { get; set; }
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt? CreatedAt { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt CreatedAt { get; set; }
#endif
        /// <summary>The display property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Display { get; set; }
#nullable restore
#else
        public string Display { get; set; }
#endif
        /// <summary>The extras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Extras { get; set; }
#nullable restore
#else
        public UntypedNode Extras { get; set; }
#endif
        /// <summary>The food property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.IngredientFoodOutput? Food { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.IngredientFoodOutput Food { get; set; }
#endif
        /// <summary>The foodId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId? FoodId { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId FoodId { get; set; }
#endif
        /// <summary>The groupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The householdId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseholdId { get; set; }
#nullable restore
#else
        public string HouseholdId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.MultiPurposeLabelSummary? Label { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.MultiPurposeLabelSummary Label { get; set; }
#endif
        /// <summary>The labelId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId? LabelId { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId LabelId { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note? Note { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note Note { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The quantity property</summary>
        public double? Quantity { get; set; }
        /// <summary>The recipeReferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealieMcp.Clients.Models.ShoppingListItemRecipeRefOut>? RecipeReferences { get; set; }
#nullable restore
#else
        public List<global::MealieMcp.Clients.Models.ShoppingListItemRecipeRefOut> RecipeReferences { get; set; }
#endif
        /// <summary>The referencedRecipe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.RecipeOutput? ReferencedRecipe { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.RecipeOutput ReferencedRecipe { get; set; }
#endif
        /// <summary>The shoppingListId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShoppingListId { get; set; }
#nullable restore
#else
        public string ShoppingListId { get; set; }
#endif
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.IngredientUnitOutput? Unit { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.IngredientUnitOutput Unit { get; set; }
#endif
        /// <summary>The unitId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId? UnitId { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId UnitId { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt? UpdatedAt { get; set; }
#nullable restore
#else
        public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput"/> and sets the default values.
        /// </summary>
        public ShoppingListItemOutOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checked", n => { Checked = n.GetBoolValue(); } },
                { "createdAt", n => { CreatedAt = n.GetObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt>(global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt.CreateFromDiscriminatorValue); } },
                { "display", n => { Display = n.GetStringValue(); } },
                { "extras", n => { Extras = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "food", n => { Food = n.GetObjectValue<global::MealieMcp.Clients.Models.IngredientFoodOutput>(global::MealieMcp.Clients.Models.IngredientFoodOutput.CreateFromDiscriminatorValue); } },
                { "foodId", n => { FoodId = n.GetObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId>(global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId.CreateFromDiscriminatorValue); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "householdId", n => { HouseholdId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "label", n => { Label = n.GetObjectValue<global::MealieMcp.Clients.Models.MultiPurposeLabelSummary>(global::MealieMcp.Clients.Models.MultiPurposeLabelSummary.CreateFromDiscriminatorValue); } },
                { "labelId", n => { LabelId = n.GetObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId>(global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId.CreateFromDiscriminatorValue); } },
                { "note", n => { Note = n.GetObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note>(global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "recipeReferences", n => { RecipeReferences = n.GetCollectionOfObjectValues<global::MealieMcp.Clients.Models.ShoppingListItemRecipeRefOut>(global::MealieMcp.Clients.Models.ShoppingListItemRecipeRefOut.CreateFromDiscriminatorValue)?.AsList(); } },
                { "referencedRecipe", n => { ReferencedRecipe = n.GetObjectValue<global::MealieMcp.Clients.Models.RecipeOutput>(global::MealieMcp.Clients.Models.RecipeOutput.CreateFromDiscriminatorValue); } },
                { "shoppingListId", n => { ShoppingListId = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetObjectValue<global::MealieMcp.Clients.Models.IngredientUnitOutput>(global::MealieMcp.Clients.Models.IngredientUnitOutput.CreateFromDiscriminatorValue); } },
                { "unitId", n => { UnitId = n.GetObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId>(global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt>(global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("checked", Checked);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt>("createdAt", CreatedAt);
            writer.WriteStringValue("display", Display);
            writer.WriteObjectValue<UntypedNode>("extras", Extras);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.IngredientFoodOutput>("food", Food);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId>("foodId", FoodId);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("householdId", HouseholdId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.MultiPurposeLabelSummary>("label", Label);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId>("labelId", LabelId);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note>("note", Note);
            writer.WriteIntValue("position", Position);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteCollectionOfObjectValues<global::MealieMcp.Clients.Models.ShoppingListItemRecipeRefOut>("recipeReferences", RecipeReferences);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.RecipeOutput>("referencedRecipe", ReferencedRecipe);
            writer.WriteStringValue("shoppingListId", ShoppingListId);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.IngredientUnitOutput>("unit", Unit);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId>("unitId", UnitId);
            writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt>("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_createdAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutOutput_createdAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_createdAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_createdAtMember1? ShoppingListItemOutOutputCreatedAtMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_createdAtMember1 ShoppingListItemOutOutputCreatedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_createdAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.ShoppingListItemOutOutputCreatedAtMember1 = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_createdAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutOutputCreatedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutOutputCreatedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_createdAtMember1>(null, ShoppingListItemOutOutputCreatedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_foodIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutOutput_foodId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_foodIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_foodIdMember1? ShoppingListItemOutOutputFoodIdMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_foodIdMember1 ShoppingListItemOutOutputFoodIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_foodId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutOutputFoodIdMember1 = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_foodIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutOutputFoodIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutOutputFoodIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_foodIdMember1>(null, ShoppingListItemOutOutputFoodIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_labelIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutOutput_labelId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_labelIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_labelIdMember1? ShoppingListItemOutOutputLabelIdMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_labelIdMember1 ShoppingListItemOutOutputLabelIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_labelId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutOutputLabelIdMember1 = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_labelIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutOutputLabelIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutOutputLabelIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_labelIdMember1>(null, ShoppingListItemOutOutputLabelIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_noteMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutOutput_note : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_noteMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_noteMember1? ShoppingListItemOutOutputNoteMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_noteMember1 ShoppingListItemOutOutputNoteMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_note();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutOutputNoteMember1 = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_noteMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutOutputNoteMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutOutputNoteMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_noteMember1>(null, ShoppingListItemOutOutputNoteMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_unitIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutOutput_unitId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_unitIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_unitIdMember1? ShoppingListItemOutOutputUnitIdMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_unitIdMember1 ShoppingListItemOutOutputUnitIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_unitId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutOutputUnitIdMember1 = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_unitIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutOutputUnitIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutOutputUnitIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_unitIdMember1>(null, ShoppingListItemOutOutputUnitIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_updatedAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutOutput_updatedAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_updatedAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_updatedAtMember1? ShoppingListItemOutOutputUpdatedAtMember1 { get; set; }
#nullable restore
#else
            public global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_updatedAtMember1 ShoppingListItemOutOutputUpdatedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput.ShoppingListItemOutOutput_updatedAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.ShoppingListItemOutOutputUpdatedAtMember1 = new global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_updatedAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutOutputUpdatedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutOutputUpdatedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealieMcp.Clients.Models.ShoppingListItemOutOutput_updatedAtMember1>(null, ShoppingListItemOutOutputUpdatedAtMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
